### ISSUE TITLE
It doesn't take the connections parameter from windows to user Proxy to connect to github

### ISSUE THREAD

**Issue by RafaAguilar** [revolunet/sublimetext-markdown-preview#168]
OS = Windows 7
Proxy= ISA Server

When i try to build with github api, it can't connect because the connection does not have the ISA server (proxy server) parameters, here is the log:

Could not import subprocess32 module, falling back to subprocess module
Traceback (most recent call last):
  File "X/urllib/request.py", line 1252, in do_open
  File "X/http/client.py", line 1049, in request
  File "X/http/client.py", line 1087, in _send_request
  File "X/http/client.py", line 1045, in endheaders
  File "X/http/client.py", line 890, in _send_output
  File "X/http/client.py", line 828, in send
  File "X/http/client.py", line 1186, in connect
  File "X/http/client.py", line 792, in _tunnel
OSError: Tunnel connection failed: 407 Proxy Authentication Required ( The ISA Server requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  )

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MarkdownPreview in C:\Users\raguilar\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 338, in convert_markdown
  File "X/urllib/request.py", line 160, in urlopen
  File "X/urllib/request.py", line 473, in open
  File "X/urllib/request.py", line 491, in _open
  File "X/urllib/request.py", line 451, in _call_chain
  File "X/urllib/request.py", line 1287, in https_open
  File "X/urllib/request.py", line 1255, in do_open
urllib.error.URLError: <urlopen error Tunnel connection failed: 407 Proxy Authentication Required ( The ISA Server requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  )>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X/subprocess.py", line 1090, in _execute_child
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "MarkdownPreview in C:\Users\raguilar\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 419, in run
  File "MarkdownPreview in C:\Users\raguilar\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 391, in run
  File "MarkdownPreview in C:\Users\raguilar\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 348, in convert_markdown
  File "MarkdownPreview in C:\Users\raguilar\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 307, in curl_convert
  File "X/subprocess.py", line 818, in **init**
  File "X/subprocess.py", line 1096, in _execute_child
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

PD:Package control connect with no issues

**Comment by DAVe3283** [comment]
I am seeing the same issue at work. Windows 7 64-bit, Sublime 3103.

```
Traceback (most recent call last):
  File "./urllib/request.py", line 1248, in do_open
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "./http/client.py", line 1198, in connect
  File "./socket.py", line 435, in create_connection
  File "./socket.py", line 426, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MarkdownPreview in C:\Users\dgmartin\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 915, in parser_specific_convert
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 469, in open
  File "./urllib/request.py", line 487, in _open
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1283, in https_open
  File "./urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "MarkdownPreview in C:\Users\dgmartin\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 1178, in run
  File "MarkdownPreview in C:\Users\dgmartin\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 768, in run
  File "MarkdownPreview in C:\Users\dgmartin\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 709, in convert_markdown
  File "MarkdownPreview in C:\Users\dgmartin\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 925, in parser_specific_convert
  File "MarkdownPreview in C:\Users\dgmartin\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 836, in curl_convert
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Our proxy doesn't require authentication, but does require sending HTTPS requests through port 8080. Port 443 is blocked. Package Control works fine in this setup for me.

**Comment by facelessuser** [comment]
The project will be maintained moving forward at https://github.com/facelessuser/MarkdownPreview. If this is still an issue for someone, please open an issue over there.
