### ISSUE TITLE
colon in URL

### ISSUE THREAD

**Issue by smi11** [revolunet/sublimetext-markdown-preview#296]
My markdown files have often links containing colon. Such markdown files fail to render with MarkdownPreview.

Example valid link:
https://courses.edx.org/courses/course-v1:BerkeleyX+GG101x+3T2015/courseware/87a692d1ab3e4e3bb0cf3d7de904c156/5b56cf2834ba4476b7e1bc8b6257280c/
(notice there is colon before BerkeleyX)

As you can see from traceback proveded below, the colon is replaced by | and some error message is reported about bad URL and rendering fails. Could this be fixed? Thanks.

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 1126, in run
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 759, in run
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 708, in convert_markdown
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 553, in postprocessor_pathconverter
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 553, in <lambda>
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 541, in repl
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 541, in <lambda>
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 281, in repl_absolute
  File "./nturl2path.py", line 26, in url2pathname
OSError: Bad URL: /courses/course-v1|BerkeleyX+GG101x+3T2015/courseware/89757399587a49b7bf91b3c907744270/dd810b686ac44f01a7ac1251ffe50ff9/

**Comment by facelessuser** [comment]
It looks like [`repl_absolute`](https://github.com/revolunet/sublimetext-markdown-preview/blob/master/MarkdownPreview.py#L276-L289) needs to be adjusted to look like:

```python
def repl_absolute(m, base_path):
    """ Replace path with absolute path """
    link = m.group(0)

    try:
        scheme, netloc, path, params, query, fragment, is_url, is_absolute = parse_url(m.group('path')[1:-1])
    except Exception:
        return link

    if (not is_absolute and not is_url):
        path = url2pathname(path)
        temp = os.path.normpath(os.path.join(base_path, path))
        if os.path.exists(temp):
            path = pathname2url(temp.replace("\\", "/"))
            link = '%s"%s"' % (m.group('name'), urlunparse((scheme, netloc, path, params, query, fragment)))

    return link
```

url2pathname shouldn't have been called if `is_url` was `true`.  Also, we should just return the link if `parse_url` fails.  I haven't verified this, but I believe this would fix the issue.  This is the same way `repl_relative` is set up, and should have been done for `repl_absolute`.

**Comment by smi11** [comment]
I tried your corrections and they work. Thanks

**Comment by smi11** [comment]
Sorry, but the issue with colon in URL returned today after update to new version.

Sample URL somewhere in text:
/asset-v1:W3Cx+HTML5.2x+4T2015+type@asset+block/StereoVolumeMeters.jpg

console log:
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 1172, in run
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 762, in run
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 711, in convert_markdown
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 556, in postprocessor_pathconverter
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 556, in <lambda>
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 544, in repl
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 544, in <lambda>
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 286, in repl_absolute
  File "./nturl2path.py", line 26, in url2pathname
OSError: Bad URL: /asset-v1|W3Cx+HTML5.2x+4T2015+type@asset+block/StereoVolumeMeters.jpg

Thanks for looking into this issue.

Kind regards
Milan

**Comment by facelessuser** [comment]
Is it because of the update or because you have a new URL corner case?  Does the original URL fail that you opened this issue with?  I suspect it doesn't.

If you compare the code in the new release to what I originally suggested, they are the same -- exactly the same.

For me to look into this new corner case, I will need you to provide an example file I can test with.  Just provide something I can copy and paste.  It is possible that Python's `urlparse` and `url2pathname` are having a disagreement about what they find valid.  I understand the the url you are providing me is technically valid, but there may be a limit to what wacky urls these methods can handle.

**Comment by smi11** [comment]
Hi,

 

That was the first thing I checked. I compared repl_absolute to previous version and they are exactly the same. 

 

I did some more experimenting and I found out that only relative url's fail. Absolute urls work fine.

 

Here are some examples from my markdown file:

 

This absolute url works

![abs image](https://courses.edx.org/asset-v1:W3Cx+HTML5.2x+4T2015+type@asset+block/frequencyResponses.jpg)

 

This relative ulrs fail

![image](/asset-v1:W3Cx+HTML5.2x+4T2015+type@asset+block/frequencyResponses.jpg)

![image](/asset-v1:W3Cx+HTML5.2x+4T2015+type@asset+block/impulsesDemo.jpg)

![image](/asset-v1:W3Cx+HTML5.2x+4T2015+type@asset+block/theTwoROutesreverb.jpg)

![image](/asset-v1:W3Cx+HTML5.2x+4T2015+type@asset+block/compressorGraph1.jpg)

 

So, if I make my links absolute they work fine. If they are relative they fail. 

 

I hope this helps.

 

Thanks and kind regards

Milan

**Comment by facelessuser** [comment]
That is what I am saying.  The reason the the fix worked for the first URL is because it identified `http://whatever` as a url and ignored trying to parse it.

Is `/asset-v1:W3Cx+HTML5.2x+4T2015+type@asset+block` an actual folder, or some kind of API call?  What do you expect Markdown preview to do with this?  Apply `https://courses.edx.org/` in front of it?  Or if it is an actual folder on your local disk, resolve it?  If you are expecting it to apply `https://courses.edx.org/` in front, it won't as it isn't aware of this.

I just want to understand the problem better before I start trying to look into this.

**Comment by smi11** [comment]
Hello,

 

I just realized that this is actually a non-issue as I have to rename those URL's to my local path anyway. I'm sorry that I bothered you about this. That main thing is that absolute paths are working just fine and relative ones don't actually matter. I should have been more careful about what I wanted. So, please forget about this.

 

Thanks again

Milan

**Comment by facelessuser** [comment]
Okay,  if you do find a legitimate issue,  just let us know.

**Comment by facelessuser** [comment]
Thinking about this more,  we should still gracefully exit and return the link unaltered even if we can't transform it.   I will at least fix that.

**Comment by smi11** [comment]
Oh yes. That would be great. Thanks again.
