### ISSUE TITLE
Preview in browser does not work on sublime text 3,mac

### ISSUE THREAD

**Issue by patsoncy** [revolunet/sublimetext-markdown-preview#309]
SublimeText  3
OS X 10.11.1
python: 2.7.10

error:
```
Traceback (most recent call last):
  File "markdown_wrapper in /Users/cy/Library/Application Support/Sublime Text 3/Installed Packages/Markdown Preview.sublime-package", line 35, in registerExtensions
  File "markdown_wrapper in /Users/cy/Library/Application Support/Sublime Text 3/Installed Packages/Markdown Preview.sublime-package", line 93, in build_extension
AttributeError: Failed to initiate extension 'headeranchor': 'module' object has no attribute 'makeExtension'

Traceback (most recent call last):
  File "markdown_wrapper in /Users/cy/Library/Application Support/Sublime Text 3/Installed Packages/Markdown Preview.sublime-package", line 35, in registerExtensions
  File "markdown_wrapper in /Users/cy/Library/Application Support/Sublime Text 3/Installed Packages/Markdown Preview.sublime-package", line 93, in build_extension
AttributeError: Failed to initiate extension 'toc': 'module' object has no attribute 'makeExtension'

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "MarkdownPreview in /Users/cy/Library/Application Support/Sublime Text 3/Installed Packages/Markdown Preview.sublime-package", line 1172, in run
  File "MarkdownPreview in /Users/cy/Library/Application Support/Sublime Text 3/Installed Packages/Markdown Preview.sublime-package", line 762, in run
  File "MarkdownPreview in /Users/cy/Library/Application Support/Sublime Text 3/Installed Packages/Markdown Preview.sublime-package", line 703, in convert_markdown
  File "MarkdownPreview in /Users/cy/Library/Application Support/Sublime Text 3/Installed Packages/Markdown Preview.sublime-package", line 1099, in parser_specific_convert
  File "markdown in /Users/cy/Library/Application Support/Sublime Text 3/Installed Packages/Markdown Preview.sublime-package", line 365, in convert
  File "markdown.extensions.tasklist in /Users/cy/Library/Application Support/Sublime Text 3/Installed Packages/Markdown Preview.sublime-package", line 62, in run
AttributeError: 'module' object has no attribute 'iterate'
```

**Comment by facelessuser** [comment]
My primary OS is OSX and I am not seeing your issue.  Have you tried restarting?

**Comment by patsoncy** [comment]
it worked! XD, thank you
