### ISSUE TITLE
[Error] on_post_save

### ISSUE THREAD

**Issue by Enteleform** [revolunet/sublimetext-markdown-preview#341]
I get this error occasionally upon saving:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 231, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 288, in <lambda>
    run_callback('on_post_save', callback, lambda: callback.on_post_save(v))
  File "MarkdownPreview in C:\Users\Fico\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 355, in on_post_save
AttributeError: 'NoneType' object has no attribute 'endswith'
```

&nbsp;
For this particular error instance, I was just working on a random `/Packages/MyPlugin/MyPlugin.py` file.
&nbsp;

-----

&nbsp;
__ST Version:__ Stable Channel, Build 3114
__OS:__ Windows 10 Pro (64-bit), Build 10586

**Comment by facelessuser** [comment]
Looks like when requesting filename from a view, if one doesn't exist, you can get this issue.  Should be pretty easy to fix.
