### ISSUE TITLE
Preview and conversion to HTML fails

### ISSUE THREAD

**Issue by enpe** [revolunet/sublimetext-markdown-preview#342]
The preview of Markdown files (`Markdown Preview: Preview in Browser >
markdown`) and the conversion to HTML (`Build with: Markdown`) fails
when images are included:

    ![image text](relative/path/to/image.png)

The error message is as follows:
 
	Traceback (most recent call last):
	  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 553, in run_
	    return self.run()
	  File "MarkdownPreview in C:\Users\plath\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 1320, in run
	  File "MarkdownPreview in C:\Users\plath\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 768, in run
	  File "MarkdownPreview in C:\Users\plath\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 709, in convert_markdown
	  File "MarkdownPreview in C:\Users\plath\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 1105, in parser_specific_convert
	  File "markdown in C:\Users\plath\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 384, in convert
	  File "markdown.treeprocessors in C:\Users\plath\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 295, in run
	  File "markdown.treeprocessors in C:\Users\plath\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 106, in __handleInline
	  File "markdown.treeprocessors in C:\Users\plath\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 239, in __applyPattern
	  File "markdown.inlinepatterns in C:\Users\plath\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 428, in handleMatch
	  File "markdown.inlinepatterns in C:\Users\plath\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 245, in unescape
	  File "markdown.inlinepatterns in C:\Users\plath\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 244, in get_stash
	NameError: global name 'itertext' is not defined

The problem arises for

* Windows 7 (didn't test other OSses)
* Sublime Text 3 (build 3114)
* Markdown Preview (1.4.0)

**Comment by facelessuser** [comment]
I'll take a look at your pull.  Looks like I probably missed this.  Thanks!
