### ISSUE TITLE
Offline installation is broken since it relies on Package Control dependencies

### ISSUE THREAD

**Issue by Mikaz-fr** [revolunet/sublimetext-markdown-preview#370]
When doing an offline installation to a machine without internet connection, versions of Markdown Preview after 1.2.0 will fail to load with the following:
```
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
Traceback (most recent call last):
  File "C:\Tools\Sublime\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Tools\Sublime\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MarkdownPreview in C:\Tools\Sublime\Data\Installed Packages\Markdown Preview.sublime-package", line 14, in <module>
ImportError: No module named 'yaml'
[...]
Package Control: Installing 2 missing dependencies
Package Control: Error downloading channel. HTTP error 403 downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, pygments, is not available
Package Control: Error downloading channel. HTTP error 403 downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, pyyaml, is not available
```

Package Control cannot resolve dependencies since no internet connection is available, so the plugin doesn't load.
There might be machines where Package Control is not installed at all by the way.

Could there be a full manuel version which doesn't rely on external packages ?

**Comment by facelessuser** [comment]
Yes, this is to make maintaining this package easier as it doesn't have to rely on maintaining dependencies as well as the code itself.

But yes, this can make installing manually more...complicated...due to the way dependencies are managed through Package Control.  Bit it is still possible.  On one of my packages that uses dependencies I was asked this same question and gave a response outlining how it can be accomplished.  You would obviously have to replace the related info with what applies to MarkdownPreview: https://github.com/facelessuser/BracketHighlighter/issues/293#issuecomment-233109077.

It is recommended to use Package Control, and if you do it this way, you will have to manage upgrades for all the moving parts. Though I would discourage going this route, I understand that some people may be adamant on doing this or they may have legitimate reasons to go this route.

**Comment by facelessuser** [comment]
I assume this answered your question.  I you have more, please respond.  I will close this issue for now.

**Comment by Mikaz-fr** [comment]
Thanks for the response, I will give it a try as soon as I get a chance. I will re-open if it doesn't work but it should be good.
As you said it's not always possible to use Package Control if you are fully offline for example.

**Comment by Mikaz-fr** [comment]
It's working fine indeed, reproducing the instruction here adapted for that package.

## How to manually install Markdown Preview

Download the latest releases of the following dependencies and unpack in the `Packages` folder as shown below:
* https://github.com/packagecontrol/pyyaml -> pyyaml
* https://github.com/packagecontrol/pygments -> pygments

Get the latest Markdown Preview release and unpack as `Markdown Preview`:
* https://github.com/revolunet/sublimetext-markdown-preview/releases -> Markdown Preview

Create a folder under `Packages` called `00-dependencies` and under that folder create a file called `00-dependencies.py`:

Copy the following code to `00-dependencies.py` (this code was taken from Package Control):
```
import sys
import os
from os.path import dirname

if os.name == 'nt':
    from ctypes import windll, create_unicode_buffer

import sublime


if sys.version_info >= (3,):
    def decode(path):
        return path

    def encode(path):
        return path

    if os.path.basename(__file__) == 'sys_path.py':
        pc_package_path = dirname(dirname(__file__))
    # When loaded as a .sublime-package file, the filename ends up being
    # Package Control.sublime-package/Package Control.package_control.sys_path
    else:
        pc_package_path = dirname(__file__)
    st_version = u'3'

else:
    def decode(path):
        if not isinstance(path, unicode):
            path = path.decode(sys.getfilesystemencoding())
        return path

    def encode(path):
        if isinstance(path, unicode):
            path = path.encode(sys.getfilesystemencoding())
        return path

    pc_package_path = decode(os.getcwd())
    st_version = u'2'


st_dir = dirname(dirname(pc_package_path))


def add(path, first=False):
    """
    Adds an entry to the beginning of sys.path, working around the fact that
    Python 2.6 can't import from non-ASCII paths on Windows.

    :param path:
        A unicode string of a folder, zip file or sublime-package file to
        add to the path

    :param first:
        If the path should be added at the beginning
    """

    if os.name == 'nt':
        # Work around unicode path import issue on Windows with Python 2.6
        buf = create_unicode_buffer(512)
        if windll.kernel32.GetShortPathNameW(path, buf, len(buf)):
            path = buf.value

    enc_path = encode(path)

    if os.path.exists(enc_path):
        if first:
            try:
                sys.path.remove(enc_path)
            except (ValueError):
                pass
            sys.path.insert(0, enc_path)
        elif enc_path not in sys.path:
            sys.path.append(enc_path)


def remove(path):
    """
    Removes a path from sys.path if it is present

    :param path:
        A unicode string of a folder, zip file or sublime-package file
    """

    try:
        sys.path.remove(encode(path))
    except (ValueError):
        pass

    if os.name == 'nt':
        buf = create_unicode_buffer(512)
        if windll.kernel32.GetShortPathNameW(path, buf, len(buf)):
            path = buf.value
        try:
            sys.path.remove(encode(path))
        except (ValueError):
            pass


def generate_dependency_paths(name):
    """
    Accepts a dependency name and generates a dict containing the three standard
    import paths that are valid for the current machine.

    :param name:
        A unicode string name of the dependency

    :return:
        A dict with the following keys:
         - 'ver'
         - 'plat'
         - 'arch'
    """

    packages_dir = os.path.join(st_dir, u'Packages')
    dependency_dir = os.path.join(packages_dir, name)

    ver = u'st%s' % st_version
    plat = sublime.platform()
    arch = sublime.arch()

    return {
        'all': os.path.join(dependency_dir, 'all'),
        'ver': os.path.join(dependency_dir, ver),
        'plat': os.path.join(dependency_dir, u'%s_%s' % (ver, plat)),
        'arch': os.path.join(dependency_dir, u'%s_%s_%s' % (ver, plat, arch))
    }


def add_dependency(name, first=False):
    """
    Accepts a dependency name and automatically adds the appropriate path
    to sys.path, if the dependency has a path for the current platform and
    architecture.

    :param name:
        A unicode string name of the dependency

    :param first:
        If the path should be added to the beginning of the list
    """

    dep_paths = generate_dependency_paths(name)

    for path in dep_paths.values():
        if os.path.exists(encode(path)):
            add(path, first=first)


add_dependency('pyyaml')
add_dependency('pygments')
```

Restart and enjoy.
