### ISSUE TITLE
Markdown Preview fails to install due to missing pygments.formatters module

### ISSUE THREAD

**Issue by Ricq** [revolunet/sublimetext-markdown-preview#400]
While installing the latest Markdown Preview using Package Control, I run into the error that the `pygments.formatters` module cannot be found. I'm installing on the latest Sublime 3.0, build 3143, and am running on Windows 10.

The console shows:
```
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MarkdownPreview in C:\Users\Rick\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 57, in <module>
ImportError: No module named 'pygments.formatters'
```

It seems that this dependency was not correctly installed.

**Comment by facelessuser** [comment]
Restart Sublime and see if there is still an issue.  Sometimes a restart is necessary after installing a plugin.  I can't see enough of the log to see if Pygments actually got installed, but if restarting does not work, you can try to run the command `Package Control: Satisfy Dependencies` (but watch the console to see when it finishes), and then restart.

**Comment by Ricq** [comment]
It works now. I don't know what happened, because I'm sure I restarted Sublime Text multiple times, as well as reinstalled the plugin and ran Satsify Dependencies, but after doing it again it's OK now. I must have done something wrong. Apologies for taking your time.

**Comment by facelessuser** [comment]
Package control can some times get broken which is why I suggested additional steps besides just restarting, but glad it's working now.
