### ISSUE TITLE
ImportError: Missing yaml dependency on ST 3.0?

### ISSUE THREAD

**Issue by samizdatco** [revolunet/sublimetext-markdown-preview#401]
Since switching from the dev channel to the 'release' version of Sublime 3.0, the markdown-preview plugin's commands have been missing from my cmd-shift-P menu. In the console I've been seeing these suspicious errors when using package-control to reinstall the plugin:

```
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'pyyaml' is not currently installed; installing...
Package Control: The dependency 'pyyaml' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["0_package_control_loader", "Rails", "Vintage"]
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
Traceback (most recent call last):
  File "/Users/xxxx/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Users/xxxx/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MarkdownPreview in /Users/xxxx/Library/Application Support/Sublime Text 3/Installed Packages/Markdown Preview.sublime-package", line 14, in <module>
ImportError: No module named 'yaml'
```

Afterwards, the ImportError stack trace pops up whenever ST3 is launched. Let me know if you need any other information to reproduce this behavior.

**Comment by facelessuser** [comment]
Run `Package Control:Satisfy Dependencies` and restart Sublime. Also, post more of you console next time showing what Sublime packages and dependencies Sublime/Package Control is loading.

**Comment by facelessuser** [comment]
By the way, when you run `Package Control:Satisfy Dependencies`, make sure you look in the console to make sure it is done before restarting.

**Comment by facelessuser** [comment]
Did the suggestion fix your issue?

**Comment by facelessuser** [comment]
Closing this as thee appears to be no actionable item.
